# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Cade DuPont"
description: "Cade DuPont is a software developer and Computer Science student at the University of Arkansas."
author:      "Cade DuPont"
