#-------------------------------
# General Site Settings

menu:
- {name: 'Resume', url: 'resume'}
- {name: 'Projects', url: 'projects'}

#-------------------------------
# Projects Section

projects:
- {name: 'Photon',                  url: 'photon'}
- {name: 'Color Frequency Palette', url: 'color-frequency-palette'}
- {name: 'Weather Wallpaper',       url: 'weather-wallpaper'}
- {name: 'The Fable of Link',       url: 'the-fable-of-link'}
- {name: 'Notion Bookshelf',        url: 'notion-bookshelf'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/cadedupont'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/cadedupont'}
- {icon: 'envelope',  link: 'mailto:cadedupont45@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  title: 'Cade DuPont'
  description: 'Cade DuPont is a software developer and Computer Science student at the University of Arkansas.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''